### ISSUE TITLE
File manager doesn't actually upload files

### ISSUE THREAD

**Issue by RoboMWM** [rymate1234/JPanel#28]
Using https://github.com/rymate1234/JPanel/commit/469cb185fe230c7b2b01552f3b5dcacc6d18f28c

On web-end, JPanel appears to properly show upload progress and a completion message. However, the file does not appear in the web view. Neither does it actually appear when I log into the server.

```yml
 user:
    password: redacted
    canEditFiles: true
    canChangeGroups: false
    canSendCommands: false
```
OS: Windows 7 (my Windows Server machine is rip at the moment)
